name: Cypress tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.12.x
      - name: Run tests
        run: |
          npm install
          npx cypress run
