name: Cypress tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
