name: Cypress tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
        env:
          ELECTRON_EXTRA_LAUNCH_ARGS: --disable-gpu
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
            name: cypress-screenshots
            path: cypress/screenshots
